- name: "World Zone"
  parent_frame_id: "camera_link"
  child_frame_id: "camera_depth_optical_frame"
  bounding_frame_id: "camera_link"
  segmentation_frame_id: "camera_link"
  z_min:  -0.45
  z_max:  0.3
  x_min:  0.0
  x_max:  1.2
  y_min: -0.7
  y_max:  0.7
  remove_surface:  true
  require_surface: true


